# Generated by Django 4.2.11 on 2024-04-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categorias", "0002_remove_categoria_nome_categoria_dt_atualiacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0004_criarpostagem_imagem_criarpostagem_imagem_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField(max_length=255)),
                ("imagem", models.ImageField(blank=True, upload_to="imagens/")),
                ("texto", models.TextField()),
                ("dt_criacao", models.DateTimeField(auto_now_add=True)),
                ("dt_atualiacao", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categorias.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="criarPostagem",
        ),
    ]
