# Generated by Django 5.0.3 on 2024-03-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_criarpostagem_imagem_criarpostagem_imagem_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criarpostagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
