# Generated by Django 5.0.3 on 2024-04-08 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inicio',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='inicio'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
