# Generated by Django 5.0.4 on 2024-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_inicio_autor_alter_inicio_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
                ('linkedin', models.CharField(max_length=250)),
                ('github', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
