# Generated by Django 5.0.3 on 2024-03-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
