# Generated by Django 4.2.11 on 2024-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_post_delete_criarpostagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="descricao",
            field=models.TextField(),
        ),
    ]
