# Generated by Django 5.0.3 on 2024-04-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data'], 'verbose_name': 'Formulario de cadastro', 'verbose_name_plural': 'Formularios de cadastro'},
        ),
    ]
