# Generated by Django 4.2.11 on 2024-04-10 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0004_cadastro_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastro",
            name="usuario",
        ),
    ]
