# Generated by Django 5.0.3 on 2024-04-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_cadastro_is_super_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='is_super_user',
        ),
    ]
