# Generated by Django 5.0.4 on 2024-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_remove_cadastro_is_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
    ]
